version: "3.7"

services:
  dev-mkrgenius-brain:
    build: .
    image: brain:dev
    ports:
      - 8000:8000
    environment:
      - OPENAI_API_KEY
    volumes:
      - ./index.json:/app/index.json
    restart: unless-stopped
