version: "3.7"

services:
  mkrgenius-brain:
    build: .
    image: ghcr.io/makerdao-data/mkrgenius-brain
    ports:
      - 8000:8000
    environment:
      - OPENAI_API_KEY
    volumes:
      - ${INDEX_DIR:-$PWD}/index.json:/app/index.json
    restart: unless-stopped
