name: 🧠 Update mkrgenius-brain index

on:
  workflow_dispatch:

jobs:
  update_index:
    runs-on: ubuntu-latest

    steps:
    - name: Executing remote SSH commands
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEV_HOST_DNS }}
        username: ${{ secrets.DEV_USERNAME }}
        key: ${{ secrets.DEV_EC2_SSH_KEY }}
        script: chmod +x ${{ secrets.DEV_TARGET_DIR }}/update_index.sh && ${{ secrets.DEV_TARGET_DIR }}/update_index.sh
