name: 🚚 Deploy mkrgenius-brain to EC2 - PROD

on:
  workflow_dispatch:
  # pull_request:
  #   types:
  #     - closed
  #   branches: [ "main", "develop" ]

permissions:
  contents: read

jobs:

  stage_1:

    # if: github.event.pull_request.merged == true

    name: Pull latest version of mkrgenius-brain
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: 'master'
        fetch-depth: 0
  
  stage_2:

    # if: github.event.pull_request.merged == true

    name: Build and re-start mkrgenius-brain
    runs-on: ubuntu-latest
    needs: stage_1
    
    steps:
    - name: Executing remote SSH commands
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.PROD_HOST_DNS }}
        username: ${{ secrets.PROD_USERNAME }}
        key: ${{ secrets.PROD_EC2_SSH_KEY }}
        script: |
          cd ${{ secrets.PROD_TARGET_DIR }}
          chmod +x ${{ secrets.PROD_TARGET_DIR }}/update_index.sh && ${{ secrets.PROD_TARGET_DIR }}/update_index.sh
          sudo docker stop mkrgenius-brain
          sudo docker rm -f mkrgenius-brain
          sudo docker build . -t brain:prod
          sudo docker run -d -v ${{ secrets.PROD_TARGET_DIR }}/index.json:/app/index.json --name mkrgenius-brain --env-file .env -p 8000:8000 brain:prod
          sudo docker system prune -f
